swagger: "2.0"
info:
  version: 0.0.1
  title: Rewards API
  description: A membership API which allows returning customers to accrue rewards and redeem those rewards when they make future purchases.
  contact:
    name: Jimmy Cann
    email: mail@jimmycann.com
    url: https://jimmycann.com
  license:
    name: MIT
    url: https://github.com/yjimk/rewards-api/LICENSE.md
host: localhost:10010
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
  - application/x-www-form-urlencoded
produces:
  - application/json
paths:
  /api/v1/users/create:
    # binds a127 app logic to a route
    x-swagger-router-controller: UsersController
    post:
      description: Creates a new user
      operationId: create
      parameters:
        - name: user
          in: body
          description: Parameters required for creating a new user
          required: true
          schema:
            $ref: '#/definitions/NewUser'
      responses:
        "200":
          description: New user has been created
          schema:
            $ref: '#/definitions/User'
        default:
          description: Unexpected Error
          schema:
            $ref: '#/definitions/Error'
  /swagger:
    x-swagger-pipe: swagger_raw

definitions:
  User:
    allOf:
      - $ref: '#/definitions/NewUser'
      - required:
        - id
        properties:
          id:
            type: integer
            format: int64

  NewUser:
    type: object
    required:
      - firstName
      - lastName
      - email
    properties:
      firstName:
        type: string
        description: The users' first name
        minLength: 2
        maxLength: 64
      lastName:
        type: string
        description: The users' last name
        minLength: 2
        maxLength: 64
      email:
        type: string
        description: The users' email address
        minLength: 3
        maxLength: 254
      mob:
        type: integer
        description: The users' mobile phone number
        minLength: 8
        maxLength: 16

  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
