swagger: "2.0"
info:
  version: 0.0.1
  title: Rewards API
  description: A membership API which allows returning customers to accrue rewards and redeem those rewards when they make future purchases.
  contact:
    name: Jimmy Cann
    email: mail@jimmycann.com
    url: https://jimmycann.com
  license:
    name: MIT
    url: https://github.com/yjimk/rewards-api/LICENSE.md
host: localhost:10010
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
  - application/x-www-form-urlencoded
produces:
  - application/json
paths:
  /api/v1/users/create:
    x-swagger-router-controller: UsersController
    post:
      description: Creates a new user
      operationId: create
      parameters:
        - name: user
          in: body
          description: Parameters required for creating a new user
          required: true
          schema:
            $ref: '#/definitions/NewUser'
      responses:
        "200":
          description: User has been updated
          schema:
            $ref: '#/definitions/User'
        default:
          description: Unexpected Error
          schema:
            $ref: '#/definitions/Error'
  /api/v1/users/update:
    x-swagger-router-controller: UsersController
    put:
      description: Updates a user
      operationId: update
      parameters:
        - name: user
          in: body
          description: Parameters required for updating a user
          required: true
          schema:
            $ref: '#/definitions/UpdateUser'
      responses:
        "200":
          description: New user has been created
          schema:
            $ref: '#/definitions/UpdateSuccess'
        default:
          description: Unexpected Error
          schema:
            $ref: '#/definitions/Error'
  /api/v1/users/{userId}:
    x-swagger-router-controller: UsersController
    delete:
      description: Deletes a user
      operationId: remove
      parameters:
        - name: userId
          in: path
          required: true
          type: integer
      responses:
        "200":
          description: A user has been deleted
          schema:
            $ref: '#/definitions/UpdateSuccess'
        default:
          description: Unexpected Error
          schema:
            $ref: '#/definitions/Error'
  /swagger:
    x-swagger-pipe: swagger_raw

definitions:
  UpdateSuccess:
    type: object
    description: On update success the API will return an object containing success as true.
    properties:
      success:
        type: boolean

  User:
    allOf:
      - $ref: '#/definitions/NewUser'
      - required:
        - id
        properties:
          id:
            type: integer
            format: int64

  NewUser:
    type: object
    required:
      - firstName
      - lastName
      - email
    properties:
      firstName:
        type: string
        description: The users' first name
        minLength: 2
        maxLength: 64
      lastName:
        type: string
        description: The users' last name
        minLength: 2
        maxLength: 64
      email:
        type: string
        description: The users' email address
        minLength: 3
        maxLength: 254
      mob:
        type: integer
        description: The users' mobile phone number
        minLength: 8
        maxLength: 16

  UpdateUser:
    type: object
    required:
      - userId
    properties:
      userId:
        type: integer
        description: The ID of the user that is to be updted
        minLength: 1
        maxLength: 11
      userData:
        type: object
        description: An object containing the user data to update. At least one paramter in this object is required
      userData.firstName:
        type: string
        description: The users' first name
        minLength: 2
        maxLength: 64
      userData.lastName:
        type: string
        description: The users' last name
        minLength: 2
        maxLength: 64
      userData.email:
        type: string
        description: The users' email address
        minLength: 3
        maxLength: 254
      userData.mob:
        type: integer
        description: The users' mobile phone number
        minLength: 8
        maxLength: 16

  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
